// import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { ThemeProvider } from '@/components/theme-provider';
import { Toaster } from '@/components/ui/toaster';
import './globals.css';
import { Metadata } from 'next';
import Header from '@/components/header';
import AppProvider from './AppProvider';
import { cookies } from 'next/headers';

const roboto = Roboto({
    subsets: ['vietnamese'],
    weight: ['100', '300', '500', '700'],
});

export const metadata: Metadata = {
    title: 'E-commerce',
    description: 'Generated by create next app',
};

async function getUserCookies() {
    const cookieStore = await cookies();
    return {
        sessionToken: (await cookieStore.get('sessionToken')?.value) || '',
        userId: (await cookieStore.get('userId')?.value) || '',
    };
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const { sessionToken, userId } = await getUserCookies();
    return (
        <html lang="en" suppressHydrationWarning>
            <head />
            <body className={`${roboto.className}`}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Header />
                    <AppProvider
                        initialSessionToken={sessionToken}
                        initialUserId={userId}
                    >
                        <main>{children}</main>
                    </AppProvider>
                    <Toaster />
                </ThemeProvider>
            </body>
        </html>
    );
}
